/**
 * Knowledge-Check question bank — imported from the original Ventilator App
 * test bank. Each question has a difficulty (Novice / Intermediate / Advanced),
 * tags for personalization, and a rationale shown after the learner answers.
 */

export type KCDifficulty = 'Novice' | 'Intermediate' | 'Advanced';

export interface KCQuestion {
  id: number;
  text: string;
  options: string[];
  correctAnswer: number;
  rationale: string;
  difficulty: KCDifficulty;
  tags: string[];
  reference: string;
}

export const KC_QUESTIONS: KCQuestion[] = [
  // ── Group 1: Novice ────────────────────────────────────────────────
  { id: 1, difficulty: 'Novice',
    text: "Which of the following best describes the primary therapeutic benefit of a mechanical ventilator?",
    options: [
      "It reverses the underlying pathology of ARDS.",
      "It acts as a means of support to maintain respiratory and metabolic functions until the patient recovers.",
      "It cures hypercapnia by permanently resetting the brainstem's respiratory drive.",
      "It prevents the atrophy of diaphragmatic muscles during critical illness.",
    ],
    correctAnswer: 1,
    rationale: "The ventilator exists solely to maintain the respiratory and metabolic functions of the lungs until the patient recovers from their illness.",
    tags: ["basic-principles", "ventilator-role"],
    reference: "The Ventilator Book, Chapter 1",
  },
  { id: 2, difficulty: 'Novice',
    text: "When setting the initial tidal volume for a patient on volume-controlled assist-control ventilation, which weight measurement should be used?",
    options: [
      "The patient's actual admission body weight.",
      "The patient's estimated dry weight.",
      "The patient's predicted body weight (PBW) based on height and gender.",
      "The patient's ideal body weight minus 10% for anatomical dead space.",
    ],
    correctAnswer: 2,
    rationale: "All tidal volumes must be expressed as mL/kg of predicted body weight (PBW), which is calculated using the patient's height and gender.",
    tags: ["initial-settings", "tidal-volume"],
    reference: "The Ventilator Book, Chapter 2",
  },
  { id: 3, difficulty: 'Novice',
    text: "What is the normal respiratory system compliance for a healthy individual, and what is the expected range for a ventilated patient?",
    options: [
      "Normal: 100 mL/cm H2O; Ventilated: 70-80 mL/cm H2O.",
      "Normal: 50 mL/cm H2O; Ventilated: 100 mL/cm H2O.",
      "Normal: 200 mL/cm H2O; Ventilated: 150 mL/cm H2O.",
      "Normal: 70-80 mL/cm H2O; Ventilated: 30-40 mL/cm H2O.",
    ],
    correctAnswer: 0,
    rationale: "The compliance of the normal respiratory system is 100 mL/cm H2O, while normal for a ventilated patient is 70-80.",
    tags: ["compliance", "basic-mechanics"],
    reference: "The Ventilator Book, Chapter 3",
  },
  { id: 4, difficulty: 'Novice',
    text: "How is the plateau pressure (PPLAT) measured, and what does it represent?",
    options: [
      "Measured during dynamic flow; represents airway resistance.",
      "Measured with a 0.5-1.0 second end-inspiratory pause; represents the equilibration of pressures and is the best assessment of alveolar pressure.",
      "Measured during passive exhalation; represents auto-PEEP.",
      "Measured at the peak of inspiration without pausing; represents the compliance of the ventilator circuit.",
    ],
    correctAnswer: 1,
    rationale: "The plateau pressure is measured using a 0.5-1.0 second inspiratory hold and represents the equilibration of pressures throughout the lungs, serving as the best assessment of alveolar pressure.",
    tags: ["plateau-pressure", "monitoring"],
    reference: "The Ventilator Book, Chapter 4",
  },
  { id: 5, difficulty: 'Novice',
    text: "You are treating a patient rescued from a house fire. The pulse oximeter reads an SpO2 of 99%, but the patient is tachycardic and obtunded. What is the most likely cause of this discrepancy?",
    options: [
      "Severe anemia causing inadequate RBCs for oxygen transport.",
      "Methemoglobinemia causing the monitor to lock at 99%.",
      "Carbon monoxide poisoning leading to falsely high SpO2 readings despite significant arterial hypoxemia.",
      "Vasoconstriction from shock causing poor peripheral perfusion.",
    ],
    correctAnswer: 2,
    rationale: "Carbon monoxide binds avidly to hemoglobin and absorbs infrared light readily, which leads to a falsely high SpO2 (98-100%) even with significant arterial hypoxemia.",
    tags: ["hypoxia", "monitoring"],
    reference: "The Ventilator Book, Chapter 5",
  },
  { id: 6, difficulty: 'Novice',
    text: "According to the 'Eleven Commandments,' what does respiratory system compliance physically measure?",
    options: [
      "The change in pressure over the change in time.",
      "The change in volume divided by the change in pressure.",
      "The amount of anatomical dead space.",
      "The plateau pressure minus PEEP.",
    ],
    correctAnswer: 1,
    rationale: "Compliance is mathematically defined as the change in volume divided by the change in pressure.",
    tags: ["compliance", "basic-mechanics"],
    reference: "The Ventilator Book, Chapter 6",
  },
  { id: 7, difficulty: 'Novice',
    text: "What is the fundamental difference between restrictive and obstructive lung diseases regarding airway mechanics?",
    options: [
      "Restrictive makes it hard to get air out; obstructive makes it hard to get air in.",
      "Restrictive makes it hard to get air in; obstructive makes it hard to get air out.",
      "Both diseases primarily increase respiratory system compliance.",
      "Both diseases primarily decrease respiratory system compliance.",
    ],
    correctAnswer: 1,
    rationale: "In restrictive lung disease, the lungs want to collapse, making it hard to get air in. In obstructive disease, it is easy to get air in, but hard to get it out due to expiratory airflow obstruction.",
    tags: ["restrictive-vs-obstructive", "basic-mechanics"],
    reference: "The Ventilator Book, Chapter 7",
  },
  { id: 8, difficulty: 'Novice',
    text: "What is the defining clinical parameter for Type I (hypoxemic) respiratory failure?",
    options: [
      "PaCO2 > 50 mm Hg.",
      "SpO2 < 95%.",
      "PaO2 < 60 mm Hg.",
      "pH < 7.30.",
    ],
    correctAnswer: 2,
    rationale: "Type I respiratory failure is explicitly defined as a PaO2 less than 60 mm Hg.",
    tags: ["respiratory-failure", "hypoxia"],
    reference: "The Ventilator Book, Chapter 8",
  },
  { id: 9, difficulty: 'Novice',
    text: "When troubleshooting a high peak airway pressure alarm, what is the first step the clinician should take?",
    options: [
      "Administer an inhaled bronchodilator.",
      "Extubate and manually bag the patient.",
      "Perform an inspiratory pause to measure the plateau pressure.",
      "Increase the PEEP to splint open the airways.",
    ],
    correctAnswer: 2,
    rationale: "The first step should be to perform an inspiratory pause and measure the plateau pressure (PPLAT) to differentiate between high airway resistance and poor lung compliance.",
    tags: ["troubleshooting", "alarms"],
    reference: "The Ventilator Book, Chapter 9",
  },
  { id: 10, difficulty: 'Novice',
    text: "According to the 'Eleven Commandments,' when should a spontaneous breathing trial (SBT) be performed?",
    options: [
      "Only after 7 days of mechanical ventilation.",
      "Readily and daily on all patients whose conditions permit.",
      "Only when the patient has a normal ABG.",
      "Never, unless the patient is on SIMV mode.",
    ],
    correctAnswer: 1,
    rationale: "Commandment X states a spontaneous breathing trial should be performed readily and daily on all patients whose conditions permit.",
    tags: ["weaning", "sbt"],
    reference: "The Ventilator Book, Chapter 10",
  },

  // ── Group 2: Intermediate ──────────────────────────────────────────
  { id: 11, difficulty: 'Intermediate',
    text: "A patient on volume assist-control ventilation has a peak airway pressure (PAW) of 45 cm H2O and a plateau pressure (PPLAT) of 22 cm H2O. What is the primary pathophysiologic problem?",
    options: [
      "Decreased lung compliance due to ARDS or pulmonary edema.",
      "Increased airway resistance due to bronchospasm, mucus plugging, or a kinked tube.",
      "Mainstem intubation.",
      "Tension pneumothorax.",
    ],
    correctAnswer: 1,
    rationale: "A high peak pressure with a low plateau pressure indicates high airway resistance, which can be caused by a kinked endotracheal tube, mucus plugging, or bronchospasm.",
    tags: ["airway-resistance", "troubleshooting"],
    reference: "The Ventilator Book, Chapter 11",
  },
  { id: 12, difficulty: 'Intermediate',
    text: "You obtain an ABG for a patient on volume assist-control. The results show pH 7.25, PaCO2 58 mm Hg, and PaO2 85 mm Hg. Which ventilator adjustment is most appropriate to correct this primary disorder?",
    options: [
      "Decrease the respiratory rate.",
      "Decrease the PEEP.",
      "Increase the respiratory rate or tidal volume.",
      "Increase the FiO2.",
    ],
    correctAnswer: 2,
    rationale: "To correct a high PaCO2 (respiratory acidosis) in Volume Assist-Control, the clinician should increase the minute ventilation by increasing the rate or the tidal volume.",
    tags: ["acid-base", "ventilation-adjustment"],
    reference: "The Ventilator Book, Chapter 12",
  },
  { id: 13, difficulty: 'Intermediate',
    text: "You note a 'shark fin' appearance on a patient's capnograph during exhalation. What does this waveform indicate, and what is a potential clinical cause?",
    options: [
      "Rebreathing of exhaled CO2, usually due to a faulty sensor.",
      "Incomplete alveolar emptying, often seen with severe bronchospasm.",
      "Sudden loss of cardiac output resulting in decreased pulmonary perfusion.",
      "A leak in the ventilator circuit or endotracheal tube cuff.",
    ],
    correctAnswer: 1,
    rationale: "With severe bronchospasm and increased airway resistance, there is incomplete emptying of the alveoli, causing the capnograph to fail to level off and adopt a shark fin appearance.",
    tags: ["capnography", "bronchospasm"],
    reference: "The Ventilator Book, Chapter 13",
  },
  { id: 14, difficulty: 'Intermediate',
    text: "A patient with COPD on assist-control ventilation exhibits dynamic hyperinflation (Auto-PEEP). Which combination of ventilator changes is most appropriate to resolve this?",
    options: [
      "Increase the respiratory rate, increase tidal volume, and lengthen inspiratory time.",
      "Lower the respiratory rate, shorten the inspiratory time, and keep tidal volume at 6-8 mL/kg.",
      "Switch to pressure-control ventilation and increase the I:E ratio to 2:1.",
      "Administer neuromuscular blockers and increase PEEP to 15 cm H2O.",
    ],
    correctAnswer: 1,
    rationale: "Treating dynamic hyperinflation involves slowing the ventilator rate (usually 10-14) and shortening the inspiratory time to allow a longer expiratory phase (I:E ratio 1:3 - 1:5), while keeping the tidal volume around 6-8 mL/kg.",
    tags: ["copd", "auto-peep"],
    reference: "The Ventilator Book, Chapter 14",
  },
  { id: 15, difficulty: 'Intermediate',
    text: "You receive an ABG with the following values: pH 7.22, PaCO2 27, HCO3 14. What is the primary acid-base disorder, and is there adequate compensation?",
    options: [
      "Metabolic acidosis with a coexisting respiratory acidosis.",
      "Metabolic acidosis with appropriate respiratory compensation.",
      "Respiratory alkalosis with appropriate metabolic compensation.",
      "Metabolic alkalosis with a coexisting respiratory alkalosis.",
    ],
    correctAnswer: 1,
    rationale: "The low pH and low PaCO2 indicate a primary metabolic acidosis. Using the compensation formula (1.5 x HCO3) + 8, the expected PaCO2 is (1.5 x 14) + 8 = 29. The measured 27 is within the +/- 2 'fudge factor', indicating appropriate respiratory compensation.",
    tags: ["acid-base", "compensation"],
    reference: "The Ventilator Book, Chapter 15",
  },
  { id: 16, difficulty: 'Intermediate',
    text: "You are evaluating an ABG: pH 7.34, PaCO2 60 mm Hg, and HCO3 32 mEq/L. The patient has a history of severe COPD. What is the correct interpretation?",
    options: [
      "Acute respiratory acidosis with no compensation.",
      "Chronic respiratory acidosis with appropriate metabolic compensation.",
      "Metabolic alkalosis with respiratory compensation.",
      "Combined respiratory and metabolic acidosis.",
    ],
    correctAnswer: 1,
    rationale: "The primary disorder is respiratory acidosis (high PaCO2, low pH). For chronic respiratory acidosis, HCO3 rises 3-4 for every 10 the PaCO2 rises above 40. A PaCO2 of 60 should raise HCO3 by 6-8 (to 30-32). The near-normal pH and elevated HCO3 indicate a chronic respiratory acidosis with appropriate metabolic compensation.",
    tags: ["acid-base", "copd"],
    reference: "The Ventilator Book, Chapter 16",
  },
  { id: 17, difficulty: 'Intermediate',
    text: "A patient on volume assist-control is showing signs of dynamic hyperinflation (Auto-PEEP) with a rising PaCO2. What is the best initial adjustment to the ventilator?",
    options: [
      "Lower the ventilator rate and shorten the inspiratory time.",
      "Increase the respiratory rate to blow off the CO2.",
      "Switch to Pressure Support Ventilation with 20 cm H2O of support.",
      "Increase the tidal volume to 10 mL/kg PBW.",
    ],
    correctAnswer: 0,
    rationale: "Dynamic hyperinflation occurs when the patient cannot exhale fully. The treatment is to slow the ventilator rate (10-14 breaths/min) and shorten the inspiratory time to give the air time to escape.",
    tags: ["auto-peep", "troubleshooting"],
    reference: "The Ventilator Book, Chapter 17",
  },
  { id: 18, difficulty: 'Intermediate',
    text: "How do you quickly estimate if a patient's hypoxemia is due to a clinically significant shunt (e.g., ARDS) using the P/F ratio?",
    options: [
      "A PaO2/FiO2 ratio less than 200 suggests a shunt fraction greater than 20%.",
      "A PaO2/FiO2 ratio greater than 400 suggests a shunt.",
      "The P/F ratio must be calculated using a pulmonary artery catheter.",
      "Multiply the SpO2 by the FiO2.",
    ],
    correctAnswer: 0,
    rationale: "The P/F ratio is calculated by dividing PaO2 by FiO2. A P/F ratio less than 200 suggests a shunt fraction greater than 20%.",
    tags: ["hypoxia", "shunt"],
    reference: "The Ventilator Book, Chapter 18",
  },
  { id: 19, difficulty: 'Intermediate',
    text: "A patient's peak airway pressure (PAW) is 40 cm H2O and their plateau pressure (PPLAT) is 38 cm H2O. Which of the following is the most likely cause?",
    options: [
      "Kinked endotracheal tube.",
      "Severe bronchospasm.",
      "Mucus plug in the proximal airway.",
      "Pulmonary edema or ARDS.",
    ],
    correctAnswer: 3,
    rationale: "High peak and high plateau pressures mean the problem is in the lungs (poor compliance), such as with pulmonary edema, ARDS, or a pneumothorax.",
    tags: ["compliance", "troubleshooting"],
    reference: "The Ventilator Book, Chapter 19",
  },
  { id: 20, difficulty: 'Intermediate',
    text: "You are adjusting settings for a patient on Pressure Assist-Control. The current set driving pressure is 15 cm H2O, yielding a tidal volume of 300 mL (approx. 4 mL/kg PBW). If the patient's lung compliance suddenly improves, what will happen to the tidal volume if the driving pressure is left unchanged?",
    options: [
      "The tidal volume will remain exactly 300 mL.",
      "The tidal volume will increase.",
      "The tidal volume will decrease.",
      "The ventilator will switch to volume-control automatically.",
    ],
    correctAnswer: 1,
    rationale: "In pressure-control, the tidal volume generated depends on compliance. If compliance improves, the same driving pressure will yield a larger (increased) tidal volume.",
    tags: ["pressure-control", "compliance"],
    reference: "The Ventilator Book, Chapter 20",
  },

  // ── Group 3: Advanced ──────────────────────────────────────────────
  { id: 21, difficulty: 'Advanced',
    text: "A patient with severe salicylate poisoning (pH 6.88, HCO3 4 mEq/L) requires intubation. Why is Assist-Control (A/C) ventilation potentially dangerous for this patient, and what is the preferred mode?",
    options: [
      "A/C limits the patient's spontaneous breaths; SIMV should be used to guarantee a high respiratory rate.",
      "A/C cannot deliver enough oxygen; High Frequency Oscillatory Ventilation (HFOV) is required.",
      "A/C volume and pressure alarms limit the massive minute ventilation needed for compensation; Pressure Support Ventilation (PSV) allows the patient's naturally high respiratory drive to achieve the required ventilation.",
      "A/C requires deep sedation which masks neurological exams; BiPAP is the only safe option.",
    ],
    correctAnswer: 2,
    rationale: "In severe acidemia, typical A/C alarms will limit the high minute ventilation the patient needs; using PSV with minimal sedation lets the patient's naturally high respiratory drive achieve 18-25 L/min.",
    tags: ["acid-base", "mode-selection"],
    reference: "The Ventilator Book, Chapter 21",
  },
  { id: 22, difficulty: 'Advanced',
    text: "A patient with ARDS has their PEEP increased from 10 to 15 cm H2O. Shortly after, the patient's blood pressure drops significantly. What is the physiological explanation for this event?",
    options: [
      "Increased PEEP stimulated a vagal response, leading to severe bradycardia and hypotension.",
      "Increased intrathoracic pressure compressed the pulmonary capillary beds, impairing venous return and decreasing left ventricular preload.",
      "High PEEP forced fluid from the interstitium into the alveoli, causing immediate cardiogenic shock.",
      "The increased PEEP relieved a cardiac tamponade, resulting in a sudden drop in systemic vascular resistance.",
    ],
    correctAnswer: 1,
    rationale: "Increased intrathoracic pressure from high PEEP lowers preload by impairing venous return (and compressing pulmonary capillary beds), which can stress ventricular function and cause hypotension.",
    tags: ["peep", "hemodynamics"],
    reference: "The Ventilator Book, Chapter 22",
  },
  { id: 23, difficulty: 'Advanced',
    text: "A patient is on a 'dual-control' mode (e.g., PRVC). The patient develops severe air hunger and takes several forceful, large-volume breaths. How will the ventilator mechanically respond, and what clinical issue might this cause?",
    options: [
      "The ventilator will switch to pressure-control mode permanently; causing hypoventilation.",
      "The ventilator will interpret the large volumes as improved compliance and lower the inspiratory pressure, leading to yo-yoing tidal volumes and severe patient-ventilator dyssynchrony.",
      "The ventilator will lock the flow rate at 80 L/min, causing auto-PEEP.",
      "The ventilator will increase the inspiratory time to match the patient's effort, causing an inverse I:E ratio.",
    ],
    correctAnswer: 1,
    rationale: "The ventilator misinterprets strong efforts as improved compliance and lowers pressure. Weaker subsequent breaths then result in low volumes, causing the vent to ramp pressure back up, creating a highly uncomfortable 'yo-yo' dyssynchrony.",
    tags: ["dual-control", "dyssynchrony"],
    reference: "The Ventilator Book, Chapter 23",
  },
  { id: 24, difficulty: 'Advanced',
    text: "A patient displays a rapidly widening gradient between their PaCO2 and their ETCO2 (e.g., PaCO2 is 55 mm Hg, ETCO2 is 20 mm Hg). Which of the following is the most likely pathophysiological mechanism?",
    options: [
      "An acute increase in intrapulmonary shunt due to extensive lobar atelectasis.",
      "An increase in dead space ventilation due to a massive pulmonary embolism or falling cardiac output.",
      "Alveolar hyperventilation caused by severe pain or agitation.",
      "A faulty endotracheal tube cuff causing a loss of inspired tidal volume.",
    ],
    correctAnswer: 1,
    rationale: "A widening gradient between PaCO2 and ETCO2 represents an increase in dead space ventilation, commonly caused by a pulmonary embolism, hypovolemia, or falling cardiac output.",
    tags: ["capnography", "dead-space"],
    reference: "The Ventilator Book, Chapter 24",
  },
  { id: 25, difficulty: 'Advanced',
    text: "According to the 'Eleven Commandments,' why is it essential to maintain tidal volumes strictly around 4-6 mL/kg PBW for ARDS patients, even if the plateau pressure is below 30 cm H2O?",
    options: [
      "Because higher tidal volumes will permanently suppress the patient's natural respiratory drive.",
      "Because the primary mechanism of ventilator-induced lung injury (VILI) is volutrauma (overdistension), which can occur independently of barotrauma.",
      "Because higher tidal volumes reliably cause oxygen toxicity.",
      "Because lowering the tidal volume is the only way to effectively increase the mean airway pressure.",
    ],
    correctAnswer: 1,
    rationale: "The major factor behind VILI is volutrauma (overdistension). Excessive tidal volumes are dangerous even if the plateau pressure is less than 30 cm H2O because volutrauma acts independently of barotrauma.",
    tags: ["ards", "vili"],
    reference: "The Ventilator Book, Chapter 25",
  },
  { id: 26, difficulty: 'Advanced',
    text: "A 23-year-old diabetic patient presents with vomiting. ABG shows: pH 7.22, PaCO2 27, HCO3 14, Na 133, Cl 90. The anion gap is 23. What is the complete acid-base diagnosis?",
    options: [
      "Pure diabetic ketoacidosis.",
      "Diabetic ketoacidosis with a concomitant metabolic alkalosis due to volume depletion.",
      "Respiratory acidosis with metabolic compensation.",
      "Non-anion gap metabolic acidosis.",
    ],
    correctAnswer: 1,
    rationale: "The gap is 23 (rise of 11). HCO3 should drop by 11 to 13. Because measured HCO3 (20) is significantly higher than expected (13), there is a coexisting metabolic alkalosis, likely from vomiting.",
    tags: ["acid-base", "dka"],
    reference: "The Ventilator Book, Chapter 26",
  },
  { id: 27, difficulty: 'Advanced',
    text: "How does the Alveolar Gas Equation explain why a patient hypoventilating on room air becomes hypoxemic even with normal lung architecture?",
    options: [
      "Hypoventilation causes a widening of the A-a gradient, indicating a shunt.",
      "As PaCO2 rises in the alveolus, it physically displaces PAO2 because the total partial pressures cannot exceed barometric pressure.",
      "High CO2 destroys surfactant, leading to immediate atelectasis.",
      "CO2 binds to hemoglobin faster than oxygen, lowering the SpO2.",
    ],
    correctAnswer: 1,
    rationale: "The partial pressure of all gases in the alveolar space can only add up to the total pressure of the air. If PaCO2 goes up, the PAO2 has to go down, lowering arterial PaO2.",
    tags: ["hypoxia", "alveolar-gas-equation"],
    reference: "The Ventilator Book, Chapter 27",
  },
  { id: 28, difficulty: 'Advanced',
    text: "What is the fundamental difference between dead space ventilation and an intrapulmonary shunt?",
    options: [
      "Dead space has a V/Q ratio of 0; Shunt has a V/Q ratio of infinity.",
      "Dead space occurs when alveoli are ventilated but not perfused; Shunt occurs when blood passes without being ventilated.",
      "Dead space is treated with high PEEP; Shunt is treated solely with 100% FiO2.",
      "Both represent a V/Q ratio of exactly 0.8.",
    ],
    correctAnswer: 1,
    rationale: "Dead space (V/Q = infinity) occurs when alveoli are ventilated but there is no perfusion. Shunt (V/Q = 0) occurs when blood passes through areas where there is no ventilation.",
    tags: ["dead-space", "shunt"],
    reference: "The Ventilator Book, Chapter 28",
  },
  { id: 29, difficulty: 'Advanced',
    text: "In a patient with severe ARDS on Pressure Assist-Control, the clinician notes the driving pressure is 18 cm H2O to achieve a tidal volume of 6 mL/kg. Based on recent literature, what does this indicate and what should be considered?",
    options: [
      "A driving pressure of 18 cm H2O is a sign of excellent compliance; increase the tidal volume to 8 mL/kg.",
      "The driving pressure exceeds the 'safe' threshold of 15 cm H2O, reflecting severe disease; consider lowering the targeted tidal volume to reduce volutrauma risk.",
      "The ventilator is malfunctioning; switch to volume control immediately.",
      "The patient needs more PEEP to push the driving pressure above 20 cm H2O.",
    ],
    correctAnswer: 1,
    rationale: "A threshold of 15 cm H2O for driving pressure is independently related to survival. If it takes more than 15 cm to get 6 mL/kg, it acts as a 'speed limit,' and the clinician should consider lowering the targeted tidal volume.",
    tags: ["ards", "driving-pressure"],
    reference: "The Ventilator Book, Chapter 29",
  },
  { id: 30, difficulty: 'Advanced',
    text: "A patient is profoundly hypoxic despite normal PaO2 and SpO2 levels, and normal cardiac output. The physician suspects cyanide poisoning. What specific type of hypoxia is this?",
    options: [
      "Hypoxemic hypoxia",
      "Stagnant hypoxia",
      "Anemic hypoxia",
      "Cytopathic hypoxia",
    ],
    correctAnswer: 3,
    rationale: "In cytopathic hypoxia, the heart pumps enough oxygen, but effective oxidative phosphorylation is inhibited (e.g., cyanide poisoning).",
    tags: ["hypoxia", "cytopathic-hypoxia"],
    reference: "The Ventilator Book, Chapter 30",
  },
];

export const KC_BY_DIFFICULTY: Record<KCDifficulty, KCQuestion[]> = {
  Novice: KC_QUESTIONS.filter(q => q.difficulty === 'Novice'),
  Intermediate: KC_QUESTIONS.filter(q => q.difficulty === 'Intermediate'),
  Advanced: KC_QUESTIONS.filter(q => q.difficulty === 'Advanced'),
};
